### ISSUE TITLE
!say output not correctly interpreting @{token} calls

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#106]
Currently, the macro
```
!roll 1d20 + @me.proficiency_bonus + @me.dexterity_mod + 2 >> ${atk1} = ${1}
!roll 1d8 + @me.dexterity_mod >> ${dmg1} = ${3}
!target "Select target."
${atk1} >= @{target}.ac ? !say "Hit ${target}.name for ${dmg1} points of slashing damage." : "Missed!"
```
*almost* works.  It rolls the dice, checks the attack, and outputs the correct response... except that instead of `@{target}.name`'s name, it inserts a link that reads `object Object`.

![image](https://user-images.githubusercontent.com/7004392/34910584-f63986bc-f87d-11e7-90ff-28e47c7a01bc.png)

Clicking on the link reloads the session.

Console output log - [bug-object-object.log](https://github.com/UnicornHeartClub/Issues/files/1628804/bug-object-object.log)
Image of the actual console output, because the log is... less than revealing:
![image](https://user-images.githubusercontent.com/7004392/34910637-3897768a-f87f-11e7-95cb-fedd2037901a.png)

**Comment by tlackemann** [comment]
So I just noticed, and I'm not sure this is the bug or not (but will write a testcase for the actual bug)

```bash
${atk1} >= @{target}.ac ? !say "Hit ${target}.name for ${dmg1} points of slashing damage." : "Missed!"
```

I think you meant to write

```bash
${atk1} >= @{target}.ac ? !say "Hit @{target}.name for ${dmg1} points of slashing damage." : "Missed!"
```

See the difference? 😄 You used `${token}.name` instead of `@{token}.name`.

Now the actual bug is that the variable should be throwing an error to you so I'm writing a test case for that.

**Comment by Pjb518** [comment]
Basically, be less shit @Aquaricat :wink:

Now getting an error for this type of problem, and it actually found _another_ error as well. The ${3} variable was used, but it should have been ${2}. Good fix. Closing.

**Comment by Aquaricat** [comment]
Death to the typo demons!
