### ISSUE TITLE
Macro title input should be focused by default when creating new macro.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#109]
Currently, when you create a new macro, it opens, but neither the macro name input or the the macro textbox are focused, so when you start typing other things start opening and closing at random, or a search might be started...

**Comment by tlackemann** [comment]
This is being deployed to beta along with an improvement to do the same when creating a new attribute

**Comment by Pjb518** [comment]
Working on the sheet macros, but not in the macro menu at the top of the screen. Is this functionality we want to exist? Or are we going to leave it as is?

**Comment by tlackemann** [comment]
Deploying a fix for that too

**Comment by Pjb518** [comment]
I don't know if you ever deployed that fix, but creating a macro on the top panel doesn't put the macro name field into focus at the moment.

**Comment by Aquaricat** [comment]
It starts in the editing textbox instead.
