### ISSUE TITLE
Unable to move tokens

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#112]
Currently I am unable to move tokens unless I have them specifically selected in the token dropdown, even if they are assigned to me (which shouldn't matter, because I'm the GM). When I attempt to drag a token to a new place on the map, nothing happens, but functionality is returned when I open the token dropdown and click the token name.

@Aquaricat doesn't seem to have this issue, so we either have something set up differently, or this is browser specific.

**Comment by Aquaricat** [comment]
An update - I just noted that the token needs to be selected as a separate click.  I can't just click-and-drag.

**Comment by Pjb518** [comment]
I think I am having the same problem, which is why clicking the token in the token dropdown allows me to move it, but I am completely unable to select a token on the map by clicking on it.

**Comment by Pjb518** [comment]
This seems to have been fixed as part of some other issue, so I'm closing this.
