### ISSUE TITLE
Multiple tokens assigned to a user

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#113]
I recently realised that it's not possible to assign multiple tokens to a single user. This is a problem, and I have a feeling it's going to be a lot of work, so I'm sorry in advance. Currently a lot of things in the game run in player context, but really this needs to be changed to character context.

There are several reasons why a player might need control of several tokens and/or character sheets.

1. Familiars
2. Ranger companions
3. Mounts
4. Summons which have to obey you, rather than ones controlled by the GM (gained through planar binding, etc.)
5. Raised undead
6. Filling in for another player if they're away for a session (I do this fairly regularly to reduce the GMs work)
7. Illusions, including things like the trickster domain duplicity
8. UA Artificer creations

This is just off the top of my head, so you can see there are many use cases here.

**Comment by Pjb518** [comment]
I should also add, thinking of future systems, some players may control a team of characters, and so will need control over each of them.

**Comment by Aquaricat** [comment]
Another example would be spell templates ala the Gabriel Pickard packs, which would potentially implemented as tokens.

**Comment by Aquaricat** [comment]
![image](https://user-images.githubusercontent.com/7004392/36446357-aa6423b4-1646-11e8-9116-d82c10741f71.png)
Implemented 2018.02.18!
