### ISSUE TITLE
Character sheet saved successfully message appearing constantly.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#121]
![image](https://user-images.githubusercontent.com/7004392/34912224-3f5e4f94-f8a1-11e7-8d92-c63b57bb6758.png)
Since the auto-save change, the top green banner that pops up when the character sheet is edited via My Vault pops up constantly, making the position of the rest of the screen bounce up and down on a regular basis.  Two thoughts:
* Make the banner absolutely positioned, taking it out of the height calculations, if you want to retain it's high visibility
* Replace the save banner with a smaller icon/label that appears next to the trash can and then fades out.
![image](https://user-images.githubusercontent.com/7004392/34912243-b9f422e2-f8a1-11e7-80e5-c5df488f9a36.png)

**Comment by tlackemann** [comment]
I removed the banner completely for the character builder. There's no need for it.

**Comment by Pjb518** [comment]
No longer getting any popups in the character creator, so I'm closing this.
