### ISSUE TITLE
Macro tab styling in SRD sheets

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#128]
Currently the macro area on the SRD sheets gives an example showing how to reference a macro. Unfortunately, it is spread over two lines, which makes it slightly hard to read. Either the sheet should be made slightly wider, or this whole reference should be given a new line. My preference would be the second option, as it accounts for people using increased font size, etc.

![image](https://user-images.githubusercontent.com/33249712/34913376-1bb4926a-f8fb-11e7-8b17-5a69413b07d5.png)

**Comment by Aquaricat** [comment]
This is an effect of the length of the randomly generated ID - once you set a specific token id from the token list, it updates: 
![image](https://user-images.githubusercontent.com/7004392/34914873-201c1234-f8e1-11e7-817b-f9e2f50559cf.png)

That said - it would be nice if you could pre-set the token id in the character sheet, and have it carry over automagically.

**Comment by Pjb518** [comment]
Oh, yeah, I know. This is a brand new sheet on an empty game, which is why it has the randomly generated ID. I just noticed the issue when scanning through the tabs and as this happens with the randomly generated IDs, and could happen if people set a long ID (long character name, for example), I think it's worth moving the ID to a new line to eliminate the possibility.

**Comment by Aquaricat** [comment]
Fair enough.  ^^

**Comment by tlackemann** [comment]
I made this so it line breaks if it is too long. This should not happen unless you have a really long tag name, the long tag name was generated by bug #114 which is now closed
