### ISSUE TITLE
Mark a character sheet as local only. (Primarily for use with desktop app)

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#13]
There may be cases where I'm just testing ideas, or working on concepts where I'm not ready for them to be uploaded to the cloud.  Maybe I don't want Dev Asstater the Halfling Busybody riding around on the cloud yet... or to ever acknowledge I came up with that horrible pun.

**Comment by khionu** [comment]
Closing this issue as won't fix, due to deprecation of desktop app. If you have any other issues, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
