### ISSUE TITLE
!test

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#135]
On Roll20, I make extensive use of a command `/talktomyself`. This command prevents anything you send to the chat from being sent to other players, and it also turns off the logs for those items. When you reload the game, anything you sent to the chat is gone.

This is a really useful feature for testing and configuring things like macro output, especially if you're doing this in an actual game. For GMs, it's also a way to test their monster's abilities without having things go to the chat and spoiling an upcoming encounter.

Importantly, this command should keep a banner up in the chat warning you that you're in talktomyself mode. It's easy to forget.

**Comment by Aquaricat** [comment]
This is basically the testing mode that was referred to in the first comment on #25 - testing mode features, as well as the ability to temporarily disable public chat (though whispers should stay available) at points.  Definitely agree, very important, useful ability, especially when it comes to setting up campaigns.

In addition to the banner, I'd suggest that the /talktomyself mode be force-set to off any time the campaign is logged into, just by default.

**Comment by tlackemann** [comment]
Is this something you toggle then toggle off or is this a command you run with parameters?

**Comment by Pjb518** [comment]
Well, we don't want to mute output entirely, because we want to see the output. We just don't want to save it, or have other people see it.

Imagine I'm setting up some custom macro for my new character, and I've typed up all the template, etc. I think it's looking good, so I send it to the chat. I look at the output and there's a mistake. I fix it in the template, but now something has broken. I do this 5 or 6 more times and then the output is now perfect. However, the chat has 8 of my potentially very long macro in it, cluttering it up like crazy. In this situation, I'd use `/talktomyself` on Roll20 to spare the other players.

**Comment by Pjb518** [comment]
> Is this something you toggle then toggle off or is this a command you run with parameters?

Regarding this, I don't see any reason we'd have to feed in parameters. We can give it a broad set of qualities which cover all of the use cases without stepping on any toes.

**Comment by tlackemann** [comment]
To be clear `!mute` would only mute output publicly. You would still see it. Perhaps a more clear word. I like the idea and it's very simple.

**Comment by Pjb518** [comment]
Okay, in that case I'd be more than happy with `!mute` and perhaps `!unmute` to remove it.

**Comment by tlackemann** [comment]
Going with `!test true|false` as I think it most directly represents what we want to do. We want temporary output and we want to hide the results from everyone else. Setting a test mode to true or false would ensure this is made clear what the results are doing.

**Comment by Pjb518** [comment]
If it's all the same, I'd prefer `!test start|end`, because it's more descriptive of the fact that this is an extended instance. It's not something you apply to a single output.

**Comment by tlackemann** [comment]
It's something you toggle though. From an interface standpoint it's either in test-mode or it's not. I think a boolean makes more sense as we already have the boolean type defined :)

**Comment by Pjb518** [comment]
Isn't this something you could just very easily change behind the scenes though? `!test true` just seems a very odd thing for something like this, and I think it actually sounds a big programmy. It's nothing close to natural language.

**Comment by tlackemann** [comment]
It's bikeshedding, I think. The command can be run in two ways, either standalone (e.g. `!test`) which will toggle the mode on/off or `!test true|false` to explicitly set if test mode is on or not.

Missing is the toggle switch above chat for test mode but that will come at a later point. Right now I'm hoping the output will be obvious which is hidden for now.

Pushing to beta

**Comment by Pjb518** [comment]
Assuming that this was indeed pushed, some of the functionality is currently missing. After using `!test` or `!test true` in the chat, everything I send to the chat is still there when I log back in. This is definitely not desirable, as chat will still become highly cluttered with items we meant to discard.

I will have to check with @Aquaricat to see if other users can see what I have typed in test mode.

**Comment by tlackemann** [comment]
I'll double check to make sure it got out. Test should not be logging anything permanent to chat

**Comment by Pjb518** [comment]
Literally just `!test` followed by a plain text chat entry, and `!test true` with a plain text chat entry.

**Comment by tlackemann** [comment]
`!test true !say 'hello'`and `!test true !roll 1d20` are working as expected for me. If i refresh I don't see the output. Make sure also that the test mode is toggled correctly. If you're using just `!test`, the UI doesn't have a way to clearly tell if it's in test mode or not

**Comment by Pjb518** [comment]
I'm not talking about using a predefined macro, so I'm not bothering to use `!say` when typing in the chat, as I think most users won't.

Regarding having the mode toggled on, I've done things like typing `!test` on new games and on a game I've just reloaded, so that's not the issue.

**Comment by Pjb518** [comment]
Here is the result of:

```bash
!test true
!say "Hello"
Hello
```

**Comment by tlackemann** [comment]
Oh you're talking without the command. Yeah that's not supported at the moment. It can be but it's not right now

**Comment by Pjb518** [comment]
Okay, no worries. Something to definitely add to the list though, because people are going to assume this is going to work.

**Comment by Pjb518** [comment]
I'm going to close this an open a new ticket for `!test` followed by chat input without an `!s` or `!w` command.
