### ISSUE TITLE
Content of compendium items is oversized

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#138]
The content of items on the vault compendium is currently very large. I realise this is not what the compendium will eventually be like, but this is something to fix when we release a final compendium.

![image](https://user-images.githubusercontent.com/33249712/34976395-c39e088e-fa96-11e7-80a7-38b051140497.png)

So that the example above is clear, this is nearly 1/6th of a 24" monitor.

**Comment by tlackemann** [comment]
Ah yes! I'd hold off on compendium for now - that was all _very_ test-y a few months back. I'm circling back next month :smile:

**Comment by Pjb518** [comment]
No problem. I'll close this for now then.
