### ISSUE TITLE
Video placement and size should persist between sessions

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#141]
Just so that users don't have to keep resetting this every session if they have a particular preference, we should be preserving the size and position of the video elements between sessions, or at least offering the option to. This is probably going to be more useful if users opt for one of the preset alignment options you mentioned on the Discord server.

**Comment by Aquaricat** [comment]
Seconded on this, because predictable, and even extremely precise placement will be invaluable to streamers.

**Comment by Pjb518** [comment]
Exactly what I was thinking. It's also important that if a player disconnects and reconnects, they show up in the same place if that's something the user wants, because people will be using overlays with character names and whatnot.

**Comment by tlackemann** [comment]
Absolutely agreed - Implementing

**Comment by tlackemann** [comment]
On beta

**Comment by Pjb518** [comment]
Working :slightly_smiling_face:
