### ISSUE TITLE
Hide video elements

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#143]
Videos are naturally going to end up taking up a fair bit of screen real estate, so users should have the option to hide or collapse the videos. This should probably have a dedicated hotkey to allow for quickly looking under an area where the videos are being displayed.

Obviously, if a user has hidden the video element, we should just stop sending them the video for the stream and reestablish it when they show the element again. Their own video will still persist unless they have toggled it off.

**Comment by tlackemann** [comment]
Collapse has been deployed to beta. Slightly different UX, collapsed will still play the video audio because I believe if I'm trying to save space, I'll still want to hear what my user is saying.

**Comment by Pjb518** [comment]
Collapse is functioning, but there is are two bugs listed in #157 and #158 . Since they already have tickets, I'm going to close this issue, as the requested functionality has now been added.
