### ISSUE TITLE
UI element z-height adjustments.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#152]
![image](https://user-images.githubusercontent.com/7004392/35014636-ed69b1d2-fad6-11e7-9526-eb1fbc2cc70e.png)
Here's another one of these little overlay issues.  It may help to set the z-index of all the major UI components - the side bar, the top bar, and the chat bar - to an obnoxiously high number, 999999999 or something.  That should hopefully eliminate these pesky overlap issues with mouse-over text appearing behind UI elements like the a/v windows, or the token list.

**Comment by Pjb518** [comment]
That is actually the exact same one as shown in #136 . Marking this as a duplicate and closing.
