### ISSUE TITLE
Unable to start video on any new game

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#159]
I've been opening several new games as part of testing another issue, and every time I've found that clicking the start camera button does nothing. It's as though the button is not responding, as the hide and mute buttons do not show, nor do we get a video feed; however, my webcam turns on each time.

Reloading the game causes the button to function as expected.

**Comment by tlackemann** [comment]
This happens when you leave then re-join. I have a several ugly workarounds but nothing I like so far. Thanks for reporting, I'm definitely aware of this just unsure how to best fix.

**Comment by Pjb518** [comment]
This appears to be working now. I had a similar bug which occurred after hiding the a/v element, but this has also been fixed.
