### ISSUE TITLE
Uncaught (in promise) DOMException: Quota exceeded error

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#167]
While doing some macro testing, I've been getting an unusual error out of the console.

![image](https://user-images.githubusercontent.com/7004392/35127028-c28b82a6-fc75-11e7-8740-4b342c74cb94.png)
[beta.poweredvtt.com-1516318389736.log](https://github.com/UnicornHeartClub/Issues/files/1644822/beta.poweredvtt.com-1516318389736.log)

Doesn't seem to be effecting anything, but...

**Comment by tlackemann** [comment]
Hah, yeah so this is one these flaws of "offline capabilities" right now. I'm unsure how to best solve this but basically you have this concept of a "service worker" in the web. It's job is to take each request, sit between it, and go "OH I HAVE THAT" and serve it from local cache.

If you open the "Applications" tab of your dev console, you'll see it's probably near the +1GB range. I need to tweak the service worker settings so it's not hogging up that much space.

Sorry if that's a lame explanation.

**Comment by Aquaricat** [comment]
Took me awhile to find it.

![image](https://user-images.githubusercontent.com/7004392/35176447-ad387ab6-fd3e-11e7-84e2-d33d73569b50.png)

**Comment by tlackemann** [comment]
Nine .. gig .. *eye twitch* ... it's fine.
