### ISSUE TITLE
Roll formula seems to be missing @me.proficiency_bonus

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#171]
While testing `!hroll`, I noticed while entering #170 that the roll formula seems to be failing to read `@me.proficiency_bonus`.  I then tested with `!roll`, and found the same thing - no value is being returned for this attribute.
Digging deeper, I attempted this:
```
!say "@{me}.proficiency_bonus"
```
Which did properly output 4 as expected for the character sheet.
```
$result = @me.proficiency_bonus
!say "${result}"
```
and
```
$result = @me.proficiency_bonus + @me.dexterity_mod
!say "${result}"
```
also work as expected.  However, when I make it a roll:
```
!roll 1d20 + @me.dexterity_mod + @me.proficiency_bonus >> $result = $1
!say "${result}"
```
Things suddenly change - note the formula on the mouse-over.
![image](https://user-images.githubusercontent.com/7004392/35200496-1d87c762-fed5-11e7-8521-ba9f0d50f855.png)

Adjusting the formula to only include the proficiency bonus gets even stranger:
```
!roll 1d20 + @me.proficiency_bonus >> $result = $1
!say "${result}"
```
![image](https://user-images.githubusercontent.com/7004392/35200507-52f97602-fed5-11e7-94d9-b39d613a7df5.png)
1d20 + 41d20 + 4? Well, the good news is that   Incidentally, per a note in the Discord, I also tried the above without any spaces between the roll and the prof bonus - same result.  Next, I tried
```
!roll 1d20+@me.strength_mod >> $result = $1
!say "${result}"
```
to see if it was specific to proficiency, which results in 
![image](https://user-images.githubusercontent.com/7004392/35200583-e44b2e56-fed6-11e7-9b6a-f16df7e07fd1.png)
Again, there's that strange middle roll.  The console output -
![image](https://user-images.githubusercontent.com/7004392/35200587-fe3bd414-fed6-11e7-92c9-ed403f7f6fd2.png)
So the result at least looks legitimate, but there's something funky going on here.  

Finally I decided to try rolling proficiency first -
```
!roll 1d20+@me.proficiency_bonus+@me.strength_mod >> $result = $1
!say "${result}"
```
![image](https://user-images.githubusercontent.com/7004392/35200611-5e900038-fed7-11e7-9f79-99fcdc40e478.png)
![image](https://user-images.githubusercontent.com/7004392/35200617-6f5407ac-fed7-11e7-95d3-bc5eb3640cac.png)
Now that reported formula is really mixed up, but strangely enough, it's reporting the correct result once you dig into the console and do the math.

**Comment by tlackemann** [comment]
If you have time today, let's review this one. I since removed the change to spaces and the tooltips were _completely_ busted before. Like completely busted. That should be corrected now

**Comment by Aquaricat** [comment]
Cool beans

**Comment by Aquaricat** [comment]
Ok, did some testing on the updates - looks like it's rolling, modifying and reporting correctly now.  I see what you mean about the tooltip output being messed up - reviewing the output, I see now that it was actually reporting the base formula twice with no spaces, explaining the strange formulas.

Cool!
