### ISSUE TITLE
Initiative macro uses the dexterity attribute, not the dexterity modifier

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#178]
When using the Initiative macro on the SRD sheet, the output in the chat showed a +10 modifier on a new character sheet with no dexterity bonus, and no value entered into the initiative box.

After testing this further, it appears that the sheet is calculating this value using the raw dexterity score, instead of using the dexterity modifier.

**Comment by khionu** [comment]
This should be a simple fix, I'll check it out today

**Comment by Aquaricat** [comment]
Resolved with UnicornHeartClub/powervtt-character-sheets#2 inclusion.  Closing!
