### ISSUE TITLE
"Unsaved changes" Warning, without any changes

### ISSUE THREAD

**Issue by khionu** [UnicornHeartClub/Issues#181]
I've been able to confirm this with map editing, character editor..... and even the marketplace

**Comment by Aquaricat** [comment]
I've seen this previously as well, but not since the review label.  @khionu, how about you?  Still seeing them pop up?

**Comment by khionu** [comment]
Strange, not anymore.... I'd like to leave this open for another week or so, jic.

**Comment by Aquaricat** [comment]
Going to go ahead and close this since the issue hasn't popped back up to my knowledge since then.
