### ISSUE TITLE
Hidden objects in the map editor

### ISSUE THREAD

**Issue by disconsented** [UnicornHeartClub/Issues#200]
The specifics are hard to pin down but I can reproduce this with most assets, essentially whenever I first go to place an object it will show up in the layer menu but will not place into the map but I have been able to reproduce this using an asset that was on the map.

**Comment by khionu** [comment]
Any chance it was placed on a different layer?

**Comment by disconsented** [comment]
I have been able to reproduce this when there were no other layers

**Comment by khionu** [comment]
Closing this issue as it has been some time with no news. If you can reproduce, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
