### ISSUE TITLE
Dragging layers needs a result indicator

### ISSUE THREAD

**Issue by disconsented** [UnicornHeartClub/Issues#207]
As is it is unclear where a layer will end up when dragging them around, all we really need to fix this is a small grey bar where the layer will end up.

**Comment by Aquaricat** [comment]
I assume here that you're referring to the list of layers in the layer sidebar - when rearranging the placement of a layer, you want some sort of indicator to appear in the list to indicate where what you're dragging will be inserted back in?

**Comment by disconsented** [comment]
Yep

**Comment by khionu** [comment]
Closing this issue as resolved. If you have any other issues, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
