### ISSUE TITLE
Clicking "open character sheet" on a token without a sheet causes the app to crash

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#212]
Clicking the "open character sheet" button crashes the app if there is no character sheet associated with the token. I think if a user attempts to open a character sheet on a token that does not have an associated sheet, they should be prompted to link a character sheet to the token.

**Comment by khionu** [comment]
Closing this issue as it has been some time with no news. If you can reproduce, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
