### ISSUE TITLE
Tokens do not expand in the token menu

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#213]
I'm having some issues with expanding tokens in the token menu at the moment. It was working, and then I collapsed the token entry, and now I can't get the tokens items to expand. It's not clear if this was caused by deleting a token, clicking in the name field, or simply collapsing the token entry. I'll experiment and see if I can get more precise steps to duplicate the issue.

**Comment by khionu** [comment]
Closing this issue as it has been some time with no news. If you can reproduce, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
