### ISSUE TITLE
Reroll and Reroll Once commands generating bad results.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#217]
With the roll command `!r 1d4rr2`, I expect a result of 3 or 4.  However...
```json
{
  "roll": {
    "id": "2e41791f-82a5-42e5-b548-c98a0b72c8d2",
    "dice": [
      {
        "id": "0f881c9c-9af5-40e9-b236-88408c4aa76a",
        "child": "b8e99503-d3fc-4b3a-af31-35399508e522",
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": true,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:14:07.650240167Z",
        "value": 3
      },
      {
        "id": "b8e99503-d3fc-4b3a-af31-35399508e522",
        "child": null,
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": false,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:14:07.650244688Z",
        "value": 1
      }
    ],
    "equation": "1d4rr2",
    "modifiers": [],
    "raw_value": 3,
    "timestamp": "2018-02-22T05:14:07.650241525Z",
    "value": 4
  },
  "execution_time": 0
}
```
We see two problems here:
* It rerolled a 3.
* It returned a value of 4 (the sum of the rolls).

Trying it again, I got...
```json
{
  "roll": {
    "id": "d8799b13-bd11-490b-8d84-19b84945ed03",
    "dice": [
      {
        "id": "0931550c-bf7a-437f-a2dd-ddbccf6d020b",
        "child": "96fa2315-0104-4174-9b33-4d53e1ec99a9",
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": true,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:17:39.893285890Z",
        "value": 2
      },
      {
        "id": "96fa2315-0104-4174-9b33-4d53e1ec99a9",
        "child": "b05dc0ff-1b3a-4e3f-92c5-2043d78ccb06",
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": true,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:17:39.893290950Z",
        "value": 3
      },
      {
        "id": "b05dc0ff-1b3a-4e3f-92c5-2043d78ccb06",
        "child": "bb99ec2a-efc3-48e4-af97-63513800e697",
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": true,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:17:39.893293131Z",
        "value": 3
      },
      {
        "id": "bb99ec2a-efc3-48e4-af97-63513800e697",
        "child": null,
        "die": "D4",
        "is_dropped": false,
        "is_rerolled": false,
        "is_successful": true,
        "max": 4,
        "min": 1,
        "sides": null,
        "timestamp": "2018-02-22T05:17:39.893294832Z",
        "value": 1
      }
    ],
    "equation": "1d4rr2",
    "modifiers": [],
    "raw_value": 2,
    "timestamp": "2018-02-22T05:17:39.893287603Z",
    "value": 9
  },
  "execution_time": 0
}
```
This time it rerolled a 2, 3, and a 3, and totaled everything out to 9.  

The first bug is probably just a > instead of a < somewhere - easy fix.  

For the second, it should be discarding the results that resulted in a reroll, IE, if you're rolling 1d4rr2, you should be rolling until you get a 3 or a 4, and the total should reflect only the roll with `is_rerolled: false`.  

I'd also suggest that in the case of a reroll, I'd like to see the child's output reflect the parent's id, along side the parent recording the child's ID.  This is just to make it absolutely clear when you're looking at the reroll what prompted it.  It's great to have the child ID point to the reroll on the parent, though - definitely keep that.

**Comment by Aquaricat** [comment]
Sub issue - on a whim, I tried running `1d4rr1`, fully expecting it to fail.  It did... after a minute with no other feedback what so ever.  On the plus side, it didn't lock out the interface, and I was able to send another roll while I was waiting.

I'd suggest adding an error check that kills the roll instantly, and reports back to the player that that's an invalid roll.

**Comment by Aquaricat** [comment]
Another item I noticed - in both examples, the JSON returned the value of the *first* (rerolled) roll as the `raw_value:` response.

**Comment by khionu** [comment]
Closing this issue as resolved. If you have any other issues, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
