### ISSUE TITLE
Player cannot move token assigned to them in standard stream app

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#219]
In addition to #218 , the user reported that their player cannot move the token they unsuccessfully assigned a character sheet to, even if they are assigned as the token owner.

The DM can still move the token.

Again, this is on the standard stream of the app, and in Firefox.

**Comment by khionu** [comment]
Closing this issue as it has been some time with no news. If you can reproduce, please come to the [Discord](https://discord.gg/ccUWwPG) and report it there, with reproduction steps if possible.
