### ISSUE TITLE
Character builder should autosave

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#32]
At the moment, it is very easy to lose your work on the character builder if you neglect to save the sheet. I think the information entered into the sheet should persist unless the sheet has been saved with no additional changes, or the sheet is discarded. If you save the sheet, or delete it, a new sheet should be presented to you when opening the character builder.

**Comment by Aquaricat** [comment]
In addition, the system should ask if the user wants to save their work when they try to leave the screen with unsaved information.

**Comment by tlackemann** [comment]
I removed the save button entirely. The sheet now live updates as I think this is more expected behavior.

**Comment by Pjb518** [comment]
Sheets do autosave, but as I mentioned in #93 , character names are not updating in the character sheet dropdown. I'll close #93, as this issue is a more closely related to the new bug.

**Comment by Pjb518** [comment]
I'm going to close this and open a new bug report. It doesn't make sense to keep listing autosave bugs here if they appear. They should get their own issues.

Autosave has been implemented and appears to be working.
