### ISSUE TITLE
Unusual initial values for new character sheets

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#38]
This issue has been mentioned before in the forums, but it hasn't yet been solved. When a new character sheet is created, the initial strength score is 10, unlike the other values which are set to 0 by default. The modifier for the strength attribute is also incorrect, set to 4, instead of 0. This will persist until a user manually enters 10 for their strength score.

Many users are not going to be familiar with the rules and may just leave this value as 10 (4).

**Comment by tlackemann** [comment]
Whoops! Sorry not sure how that slipped through, fixed now
