### ISSUE TITLE
NPC sheets revert to being PC sheets after leaving the character sheet panel

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#39]
This issue has been mentioned on the forums here: https://support.poweredvtt.com/t/npc-sheets-revert-to-pc-sheets/499/1

When a sheet is set to NPC, the sheet reverts to being a PC sheet as soon as a user clicks off the Character Sheet tab. Setting the attributes manually causes the sheet to revert to an NPC sheet instead.

**Comment by Aquaricat** [comment]
Can confirm this bug, I've seen it too.

**Comment by tlackemann** [comment]
Fixed!
