### ISSUE TITLE
Help introduction ends on 8 of 12

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#44]
When going through the help introduction, the tooltips disappear after clicking next on number 8. The help icon is still highlighted, but nothing else shows up. Exiting the help intro and clicking back on it doesn't resolve the issue, as progress is rightly saved: tooltip number 9 just doesn't show properly, which means you can't continue the introduction.

**Comment by tlackemann** [comment]
Fixed!
