### ISSUE TITLE
Character sheet stats should default to 10

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#49]
An absolute nitpick here, but I think character sheets should set the core attributes to 10, just to keep the modifiers correct from the initial load. Also, 10 is a very common value for attributes, and it will ultimately mean a lot less editing for people as they make dozens or even hundreds of sheets over the course of using the software.

**Comment by Aquaricat** [comment]
This.  >_>

**Comment by Aquaricat** [comment]
I see this has been normalized out to 0's across the board.  Closing!  ^^

**Comment by Pjb518** [comment]
Reopening as I think 10 is a better default value than zero. It is a common value than 0, so defaulting to 10 will reduce setup time, and also keep the starting mods correct.

Easy fix, so I don't think there's much point in compromising here.

**Comment by Pjb518** [comment]
New sheets are all defaulting to 10, as requested, so I'm closing this one.
