### ISSUE TITLE
GM notes should not be visible to players

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#50]
I may have missed the purpose of GM notes, but my understanding is that these are notes _for_ the GM, not _to_ the GM. If the former is true, then these should not be visible to the player creating or using a character sheet, as there may be secret information in these notes which the GM does not want the player to be privy to. Perhaps the player has a cursed item, and the GM wants to keep a note of that on the player sheet, for example, along with information about how long they've had it, and cumulative effects, etc. All things the player clearly shouldn't know.

Currently GM notes are visible to players.

**Comment by Aquaricat** [comment]
What I took away from what @tlackemann was saying the other day is that the notes section is going to be more of a journal/blog type format, where the current text box is replaced with a rich-text editor that outputs Markdown-formatted content, and stores entries.  This actually makes a lot of sense to me, as it allows for much better management of notes.  The player notes will function in the same manner.

Did I interpret that intent correctly, Tom?

**Comment by tlackemann** [comment]
GM Notes are for GMs only. I very well could have missed the permission development step on this one.

Fixing

**Comment by Pjb518** [comment]
Just checked that I can't access GM notes on @Aquaricat 's game, and the GM notes tab no longer appears for me, so this is working as expected.
