### ISSUE TITLE
Prompt options appear in a random order

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#59]
I've made a test prompt macro with just two options, and the options do not show up in a consistent order. If a user has made a macro with a more extensive list, such as a skill macro, where options might be listed alphabetically, this could become something of a headache. Having an alphabetised list put in random order will make things harder to find.

Also, the number system allowing for quick select remains in order, which means that if you know where an option is, and you simply click through without reading, you're likely to get an incorrect result, as options won't be where you expected.

**Comment by Pjb518** [comment]
![image](https://user-images.githubusercontent.com/33249712/34769149-4dc15258-f5fd-11e7-9986-403b4b23dad0.png)

**Comment by tlackemann** [comment]
This is due to how JS objects work, objects don't guarantee order (since we're using a simple key:value object)

This can be fixed by instead keeping the integrity of the array instead of passing off an object. Looking into

**Comment by Pjb518** [comment]
Just wanted to update you on this. The bug is still present on beta.

**Comment by tlackemann** [comment]
Can you provide the example you're running?

**Comment by tlackemann** [comment]
You're right, sorry. 0.4.4 fixes this.

**Comment by Pjb518** [comment]
Seems to have worked! :smile:
