### ISSUE TITLE
Limit strings to text within quotes

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#65]
As mentioned in #60 , using keywords instead of && and || might be easier for users less familiar with programming. If things like 'and' and 'or' are reserved, along with 'default', as mentioned in #58 , it makes sense to limit strings to text within quotes, just to prevent ambiguity.

**Comment by Aquaricat** [comment]
The argument for enforcing quoted strings gets stronger, now that we can do bracketed ${vars} and are planning to parse them directly from a string - explicitly marking the string should make other parsing easier, too.

**Comment by Pjb518** [comment]
Pretty sure this is fine now, as we only accept single words without quotes, and those are unlikely to be the keywords we've chosen as they're conjunctions for the most part, or unusual nouns, like default.
