### ISSUE TITLE
Option to prevent rolls outputting to the chat

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#66]
There needs to be a way to keep rolls from being sent to the chat, for example if using a roll as an intermediary step in a larger process. When storing a roll in a variable for example, we don't necessarily want to output it to the chat.

An important thing to consider here is that the source of values that we place, for example, inline, must be traceable. Users shouldn't be able to obfuscate the source of values just by placing the roll in a variable, allowing them to surreptitiously replace the roll with perhaps a prompt input.

**Comment by Aquaricat** [comment]
`!hroll` has been in for awhile now!  Closing!
