### ISSUE TITLE
Badly formatted rolls can cause the app to crash

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#67]
I recently attempted the following to see if it would be correctly processed - as expected, it was not.
```bash
$var = 2
$var2 = 6
!roll $vard$var2
```
However, in addition to not producing the required output (it outputs zero every time), clicking the roll in the chat causes to app the crash. I think you should be aware of this, because people are definitely going to write things like this, where !roll is fed a badly formed input.

I think this clearly also highlights the need for the optional curly brace syntax for variables, mentioned in #63 .

**Comment by Aquaricat** [comment]
Proper support for `${var1}d${var2}` rolls was added awhile ago, closing!
