### ISSUE TITLE
Campaign Editor is not saving campaign/area names.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#74]
![image](https://user-images.githubusercontent.com/7004392/34803635-e1889bc2-f639-11e7-93f5-070f280d25dc.png)
I've been trying to adjust the name of my campaign, as well as the two areas that I've added for testing purposes in my list.  They default to A Magnificent Journey, Area 1 and New Area 2, respectively.  Above is the picture of all the values changed, and saved (note the save button is disabled.  However, when I go back to the campaign list...

![image](https://user-images.githubusercontent.com/7004392/34803671-181d7054-f63a-11e7-9432-6c0b65ace898.png)

And the areas...
![image](https://user-images.githubusercontent.com/7004392/34803679-2aeab49e-f63a-11e7-8fb8-f677ccac2ffc.png)

Something's not connecting here.

**Comment by tlackemann** [comment]
Thank you for reporting. This is being deployed to beta

**Comment by Aquaricat** [comment]
I can confirm that the titles are now saving correctly.  Thanks!
