### ISSUE TITLE
Option to go directly into campaign editor, rather than game mode

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#75]
![image](https://user-images.githubusercontent.com/7004392/34803714-68f5ce54-f63a-11e7-9267-5e5e3232d0e2.png)
It'd be nice to be able to go straight to the campaign editor from the campaign list, without pausing in the main game mode.

**Comment by tlackemann** [comment]
![https://media3.giphy.com/media/3o8doViOoBPrRJl90k/giphy.gif]

**Comment by Pjb518** [comment]
Buttons added and seem to be working as expected!
