### ISSUE TITLE
Popup should display name of character being imported to token on verification.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#76]
![image](https://user-images.githubusercontent.com/7004392/34803830-10a5cb22-f63b-11e7-8d3b-445620c89643.png)

Just for sanity's sake, it'd be nice if this popup included the name of the character sheet being imported, so that if the wrong sheet is selected, it can be canceled out of.

**Comment by Pjb518** [comment]
The alert now tells users which character sheet they are importing, so I'm closing this.
