### ISSUE TITLE
Focus should be returned to the chat if there is no other focus

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#78]
At the moment, executing a macro from the chat with, say, a prompt, causes the chat input to stop being the focus. You can't simply write something afterwards and have it type in the chat input without first reclicking the text area. Given that the chat is really the source of everything, especially given how we execute macros right now, it should basically always be in focus in my opinion. The only exception is when a user explicitly clicks a different text box, or when there is a prompt, etc. Everything else is done with the mouse, so there is really no reason to not have the chat input available at all times without having to reselect it.

**Comment by Aquaricat** [comment]
To add onto this, there should be a shortcut key that focuses and places the cursor in the chat input as well.

**Comment by tlackemann** [comment]
This was the behavior before but when I added `!target` I purposely deselected it to prevent users from typing in things while a target was active.

I pushed a fix that disables the text output when a target is active but also restores the previous behavior of keeping focus on the input.

**Comment by Pjb518** [comment]
The fix seems to have worked, but I think we should also make the chat come back into focus if a player clicks off a token, and thus has nothing selected. This ties into what Aquaricat mentioned in #100 . The issue now is that there are a number of hotkeys bound to the menus at the top of the screen. Obviously we would have to bind them to something else, and alt + their current keys makes the most sense. This would also allow them to be opened while the chat was in focus.

**Comment by tlackemann** [comment]
What if I add a new hotkey for "C" to focus chat?

I don't think it makes sense to focus chat after a token is deselected, IMO. I think a hotkey would solve this easily.

**Comment by Pjb518** [comment]
Fair enough.

C hotkey is working to select chat as is the new S hotkey for character sheets. Closing this one.
