### ISSUE TITLE
Rolling a custom die with multiple negative numbers causes a parsing error for the new 1d[x, y, z] syntax

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#81]
Rolls such as `!r 1d[-3, -2, -1]`, or indeed any roll using the new syntax which includes more than one negative number causes a parsing error. `!r 1d[-1, 1]` or `!r 1d[-2, 1]` function correctly with just one negative value.

**Comment by tlackemann** [comment]
Ah, so this is probably a problem with the API more than anything else.

This works: https://roll.poweredvtt.com/v1/1d[-3,-2,-1]
This doesn't: https://roll.poweredvtt.com/v1/1d[-3, -2, -1] (notice the spaces)

I'll need to evaluate how to better handle this on the API but I can temporarily solve this on the client-side by just stripping the whitespaces

**Comment by tlackemann** [comment]
Oh wait! So the bug is parsing when you have a space inbetween a comma and a negative number. Fixing.

**Comment by Aquaricat** [comment]
![image](https://user-images.githubusercontent.com/7004392/34839029-d9147e66-f6c5-11e7-956e-e6fc404472ee.png)
Possible this hasn't actually pushed to the beta server yet, but that's what I got when I tried rolling.

**Comment by Aquaricat** [comment]
Derp, wrong system.  `!roll`, not `/roll`
That said, still getting a general failure error when using the correct command.

**Comment by Aquaricat** [comment]
![image](https://user-images.githubusercontent.com/7004392/34839176-4c911296-f6c6-11e7-954e-1e2ddfbb70e3.png)

Exited Chrome completely and tried again - appears to be working, however, this should be reporting my name, not system...

**Comment by Aquaricat** [comment]
Tested and resolved!  Closing!
