### ISSUE TITLE
Can't edit the name of a macro after saving it.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#84]
![image](https://user-images.githubusercontent.com/7004392/34834696-3bfb6660-f6b8-11e7-8b1e-09809f0e99a8.png)
This may be intended behavior (?), but I can't change the name of the macro by clicking on it, nor do I see an option to adjust it elsewhere.

**Comment by tlackemann** [comment]
Intended for the moment due to dev restrictions (time). Can be addressed at a later point.

**Comment by Aquaricat** [comment]
I'll go ahead and close this issue out for now, as it's not a *huge* issue.  Thanks!
