### ISSUE TITLE
Update Macro Documentation link to point to the wiki.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#89]
The link pointing to the Macro Documentation in the Macros column on the character sheets should be updated to point to the new Wiki, rather than the old Github page.

![image](https://user-images.githubusercontent.com/7004392/34838955-9498db24-f6c5-11e7-99ea-1d51ce264dd1.png)

**Comment by tlackemann** [comment]
Deploying now, good catch!

**Comment by Aquaricat** [comment]
I see it now in game mode.  Cool beans.  ^^
