### ISSUE TITLE
Adjustment to layout of macro widget on character sheet.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#92]
![image](https://user-images.githubusercontent.com/7004392/34850022-f5e490d4-f6e9-11e7-9740-8cc2c51f0e3c.png)
I'm thinking that the current layout could make better use of the available space.  Rather than placing the macro name to the left, then the editor in a new column, and a save/edit button (for a new macro), or a delete button (for the rest of the time) instead maybe something like:
```
[Macro Name _______________] {{SaveIcon}} {{CancelIcon}}/{{DeleteIcon}}
-----------------------------------------------------------------------
| Macro editor                                                                                    |
|                                                                                                         |
-----------------------------------------------------------------------
```
This would make the macro editing text box substantially larger and easier to read while editing, and better use the available space since *usually* the macro name isn't going to be terribly long.

**Comment by Aquaricat** [comment]
The more I think about this proposition, and work with the macro editor, the more I think this idea could be further improved.  Currently, each macro receives its own row in a list which displays all macros; each widget shows the name, and a textbox with the macro content in it.  What if this basic concept was changed?  
Rather than displaying all macros all the time, which depending on the player could be a *lot* of macros (I have sheets on R20 with 50+ abilities, for example), show just a list the macro names, with an edit and delete icon.  When the edit button is clicked, minimize the list in some way, then replace it with an editing interface similar to the example above, where the text box is maximized as much as possible.
The advantage to this is that it's less for a user to sort through when they're looking at the attributes/macro page, and much easier to see the whole of a macro while editing it.  It would also open up room to add the proposed output console #24.  Finally, it could prove advantageous in the future if the macro editor is extended with, for example, buttons that insert basic commands like `!say` or `!roll`, or if an extensive implementation of #99 is ever done with things like syntax highlighting and syntax checking.

**Comment by tlackemann** [comment]
I could also see this being useful to simply "click" on a macro from the sheet to run it as opposed to finding the name, finding the macro name and executing.

Great idea. I'll look into

**Comment by Pjb518** [comment]
Definitely agree with all of the above. At the moment I don't edit macros on the sheet at all. I either write them externally and copy them in, or I write them in the global macros tab, where I can extend the text area as much as I want.

Launching macros from the sheet is also a big bonus :smile:

**Comment by tlackemann** [comment]
![2018-01-13-114718_509x555_scrot](https://user-images.githubusercontent.com/2633753/34908070-d364cc3a-f857-11e7-9151-63ca06120321.png)

This is going out to beta now

**Comment by Aquaricat** [comment]
I like this new functionality - much cleaner.  I'd make the default height of the text boxes taller - double the current height, probably.  Also, I would disable manual horizontal resizing, as it can break the layout - just have the box stretch to the width of the column.
Last - the edit gear seems to require some rather precise clicking.  I've noticed this in other places throughout the UI as well - you have to be right at the middle of a lot of the close boxes for things like the players/areas/tokens list; clicking on the edges is treated as clicking on the background (in this case, it executes the macro, which is a nice bonus, BTW.  ^^).

**Comment by Pjb518** [comment]
I like this a lot. Much better than before.

I agree with aquaricat regarding the horizontal resizing. This should be disabled, and it also isn't necessary if we can resize vertically anyway.

As for the default size of the boxes, I think double the current size is a but too much, but 150% would work nicely. Would give about 9 lines of input, which is plenty for most things users will be doing with this.

I'd suggest wrapping the gears in a little, invisible button box. Just make it square, and set the gear in the centre. This will also make the gears feel less squashed on the side, because it will add padding, and it means you can catch clicks which just miss the icon. If anyone is clicking anywhere near that cog, we can quite safely assume they're trying to click the cog.

**Comment by Aquaricat** [comment]
What I always liked to do was 
```
<style>
  a.buttonBox {display: inline-block; height: (whatever the line height is);}
</style>
```
Which turns it into a full inline block, rather than just the text within the `<a>` being the link.

**Comment by Pjb518** [comment]
I'm going to close this and open a new issue for the resizing problem. It is serious, because it causes styling problems, and I don't want it to get lost on this ticket.
