### ISSUE TITLE
Saving a new macro does not save the entire sheet.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#93]
When creating a new macro, there's an explicit save button.  It's very strange, then, that when I click on the save button, the macro isn't available - until I save the rest of the sheet.  It also adds a bit of confusion when editing, since the save button doesn't return when you edit an already existing macro.

Ideally, saving a macro should be able to push the new macro live automatically, and when the macro is then edited it should show the save/cancel link again to either save the changes explicitly, or cancel out and restore the original text (in case the user changes their mind on the edit.  

In lieu of that, the save/cancel button should be completely removed, including from a new macro, so that the user is forced to click on the sheet save button.  This is definitely the less preferred option, as it's begging for unintentional bugs to be introduced to working macros.

**Comment by tlackemann** [comment]
I'm going to remove the save button completely and have focus/unfocus'ing elements auto-save any changes. I find myself fumbling with the save button too

**Comment by Pjb518** [comment]
Sheets are saving as expected, but character names are not updating on the character sheet dropdown when the sheet autosaves.

**Comment by Pjb518** [comment]
Issue #32 is more closely related to the new bug, so I'm closing this as the desired functionality for macros is working.

**Comment by Aquaricat** [comment]
Reopened briefly -
I do think there should still be a macro-level save link/icon, which could actually do nothing at all - it'd be there specifically as a placebo for users to click on, thus exiting focus on the macro textbox and saving.  

That said, enabling auto-save features is a great improvement.  Cheers!

**Comment by tlackemann** [comment]
Added

**Comment by Pjb518** [comment]
Added and functioning as expected.
