### ISSUE TITLE
Tabletop Display Mode/No UI Mode

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#95]
From https://support.poweredvtt.com/t/map-display-only-option/529, suggestion by Snalajxb565.

This would basically be a (nearly) UI-less format for game-mode, displaying *just* the map and certain effects/fow/etc.

**Comment by tlackemann** [comment]
This was released to beta

**Comment by Pjb518** [comment]
Seems to be working very well. There is a slight aesthetic issue, which you can see below, because the top bar cuts off where the side bar would usually be.

![screenshot from 2018-01-13 16-16-59](https://user-images.githubusercontent.com/33249712/34907351-9551e89e-f87d-11e7-9e7f-acec43f5c6a6.png)

**Comment by tlackemann** [comment]
Not much I can do there - If I were to stretch it, when you hover over the left sidebar it will partially cover it.

Not much a win there unless I partially faded out the left sidebar so it's known it's always there.

Open to suggestions

**Comment by Pjb518** [comment]
> Not much I can do there - If I were to stretch it, when you hover over the left sidebar it will partially cover it.

By this do you mean the left bar will partially cover the content of the top bar? Or the top bar will be rendered on top of the left bar?

The former can be corrected by just adding padding to the left of edit when it goes into full screen mode. We don't care about having both bars visible at the same time in this mode, so having the left bar block access to the top by overlapping isn't an issue.

**Comment by tlackemann** [comment]
Oh I love the idea of padding - okay doing that. Thank you!

**Comment by Aquaricat** [comment]
Question: Is there a way to have this automatically trigger the browser's full screen mode?  Granted, it's not hard to hit F11, but seems like this would be the perfect use for that automation.

**Comment by Pjb518** [comment]
Looks much, much better!

Regarding the full screen thing, there is a [Javascript full screen API](https://davidwalsh.name/fullscreen) which works cross browser and is designed for things like setting a video to full screen. It has to be triggered by a user (can't be automatic), but as we're triggering this with a button press, it should work fine.

**Comment by Pjb518** [comment]
No UI mode currently doesn't seem to have any bugs, and I think launching full screen mode is something worth discussion as a separate issue. It might be something we add to the configuration options, as I can see some users not wanting this. No UI mode isn't just going to be for people playing offline.
