### ISSUE TITLE
Couple syntax mistakes in the !whisper documentation.

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#96]
![image](https://user-images.githubusercontent.com/7004392/34855815-5f7865b2-f707-11e7-951d-3a3508437c3f.png)

- [x] Initial example says `!say`, not `!whisper`.
- [x] Extra 'j' in `Tokjen` under type on the `to` and `from` line of the argument breakdown.

**Comment by Pjb518** [comment]
These have been corrected, so I'm closing this.
