### ISSUE TITLE
Function sidebar overlaps text on campaign browser

### ISSUE THREAD

**Issue by Aquaricat** [UnicornHeartClub/Issues#97]
![image](https://user-images.githubusercontent.com/7004392/34901739-31876914-f7d4-11e7-8bf4-b10afa33419e.png)
I think this is after #75 's changes, the text is being overlapped by the left sidebar a little bit.

**Comment by Pjb518** [comment]
Either this has been fixed, or it's browser specific. Not getting this on Chrome 64.0.3282.24 (Official Build) beta (64-bit).

![image](https://user-images.githubusercontent.com/33249712/34904360-9ef28194-f844-11e7-8ec6-7999f140777f.png)

**Comment by tlackemann** [comment]
This has been corrected in an update, closing
